name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Install docker compose
        run: sudo apt-get update && sudo apt-get install docker-compose

      - name: Run Hasura DB
        run: pnpm dev:db:ci

      - name: Run Tests
        run: PRIVY_APP_ID=${{ secrets.PRIVY_APP_ID }} PRIVY_APP_SECRET=${{ secrets.PRIVY_APP_SECRET }} JUPITER_URL=${{ secrets.JUPITER_URL }} QUICKNODE_ENDPOINT=${{ secrets.QUICKNODE_ENDPOINT }} QUICKNODE_TOKEN=${{ secrets.QUICKNODE_TOKEN }} FEE_PAYER_PRIVATE_KEY=${{ secrets.FEE_PAYER_PRIVATE_KEY }} OCTANE_TRADE_FEE_RECIPIENT=${{ secrets.OCTANE_TRADE_FEE_RECIPIENT }} pnpm test
        env:
          PRIVY_APP_ID: ${{ secrets.PRIVY_APP_ID }}
          PRIVY_APP_SECRET: ${{ secrets.PRIVY_APP_SECRET }}
          JUPITER_URL: ${{ secrets.JUPITER_URL }}
          QUICKNODE_ENDPOINT: ${{ secrets.QUICKNODE_ENDPOINT }}
          QUICKNODE_TOKEN: ${{ secrets.QUICKNODE_TOKEN }}
          FEE_PAYER_PRIVATE_KEY: ${{ secrets.FEE_PAYER_PRIVATE_KEY }}
          OCTANE_TRADE_FEE_RECIPIENT: ${{ secrets.OCTANE_TRADE_FEE_RECIPIENT }}

      - name: Teardown
        run: pnpm dev:teardown
